server:
  port: 9005 # 服务提供方

# 指定当前eureka客户端的注册地址,
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  instance:
    hostname: 139.224.251.185

#当前服务名称
spring:
  application:
    name: map