server:
  port: 9005 # 服务提供方

# 指定当前eureka客户端的注册地址,
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:9000/eureka/
  instance:
    hostname: 47.102.204.30

#当前服务名称
spring:
  application:
    name: map