#普通的key value
name: lzr

#对象
student:
  name: lzr
  age: 2

#行内写法
students: {name: lzr,age: 2}

#数组
pets:
  - cat
  - dog
  - pig

pet: [cat,dog,pig]



person:
  name: lzr${random.uuid}
  age: ${random.int}
  happy: false
  birth: 2001/04/30
  maps: {k1: v1,k2: v2}
  lists:
    - code
    - music
    - boy
  dog:
    name: ${person.hello:hello}_旺财
    age: 3